services:
  postgres:
    image: timescale/timescaledb:latest-pg12
    container_name: postgres
    command:
      postgres
      -c shared_preload_libraries=timescaledb
      -c archive_mode=on
      -c archive_command=test\ \!\ -f\ /wal_archive/%f\ \&\&\ cp\ %p\ /wal_archive/%f
      -c archive_timeout=60
      -c huge_pages=off
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - wal_archive:/wal_archive

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5431:80"
    depends_on:
      - postgres

  spark:
    image: jupyter/all-spark-notebook:x86_64-spark-3.5.0
    container_name: spark
    ports:
      - "8888:8888"
      - "4040:4040"
    command: >
      start-notebook.py
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.allow_origin='*'
      --ip=0.0.0.0
      
    depends_on:
      - postgres

volumes:
  pgdata:
  wal_archive: