apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: grafana-postgresql-datasource
    uid: afnnbaf3dik8we
    url: timescaledb:5432
    database: energydb
    user: report_reader
    secureJsonData:
      password: sifre456
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true