version: '3.8'

services:
  spark:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: spark_dev
    ports:
      - "8888:8888"
      - "4041:4040"
    volumes:
      - ..:/home/jovyan/work:cached
    command: >
      start-notebook.py
      --ServerApp.root_dir='/home/jovyan/work'
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.allow_origin='*'
      --ip=0.0.0.0
    networks:
      - steelenergy_network
      
networks:
  steelenergy_network:
    external: true